---------------------------O2C CYCLE------------------------------------------
---------------------AFTER ENTERING THE ORDER--------------------------------

--ORDER_NUMBER: 70426

SELECT HEADER_ID, ORDER_NUMBER, FLOW_STATUS_CODE, BOOKED_FLAG, ORG_ID
FROM OE_ORDER_HEADERS_ALL
WHERE ORDER_NUMBER='70426';

-- HEADER_ID: 583562

SELECT HEADER_ID, LINE_ID, flow_status_code, line_number, ordered_item, ordered_quantity, unit_list_price_per_pqty
FROM OE_ORDER_LINES_ALL
WHERE HEADER_ID='583562';

--LINE_ID: 772490

-------------------AFTER BOOKING THE ORDER----------------------------------

SELECT HEADER_ID, ORDER_NUMBER, FLOW_STATUS_CODE, BOOKED_FLAG, ORG_ID
FROM OE_ORDER_HEADERS_ALL
WHERE ORDER_NUMBER='70426';

SELECT HEADER_ID, LINE_ID, flow_status_code, line_number, ordered_item, ordered_quantity, unit_list_price_per_pqty
FROM OE_ORDER_LINES_ALL
WHERE HEADER_ID='583562';


SELECT INVENTORY_ITEM_ID, RELEASED_STATUS, CUSTOMER_ID, delivery_detail_id
FROM WSH_DELIVERY_DETAILS
WHERE source_header_id='583562';

--DELIVERY_DETAIL_ID: 6307213

SELECT *
FROM WSH_DELIVERY_ASSIGNMENTS
WHERE DELIVERY_DETAIL_ID='6307213';

--DELIVERY_ASSIGNMENT_ID: 6392478

-----------------------AFTER PICK RELEASE-----------------------------------

SELECT INVENTORY_ITEM_ID, RELEASED_STATUS, CUSTOMER_ID, delivery_detail_id
FROM WSH_DELIVERY_DETAILS
WHERE source_header_id='583562';

--CUSTOMER_ID: 1290
--INVENTORY_ITEM_ID: 8063

SELECT *
FROM WSH_DELIVERY_ASSIGNMENTS
WHERE DELIVERY_DETAIL_ID='6307213';

--DELIVERY_ASSIGNMENT_ID: 6392478
--DELIVERY_ID: 6310966


----------------------------------------------------------------------- 

SELECT *
FROM FND_USER
WHERE USER_NAME='XXCTS_RAJDEEP';

--USER_ID:  1017549
 

SELECT INTERFACE_HEADER_ATTRIBUTE1
FROM RA_CUSTOMER_TRX_ALL
WHERE INTERFACE_HEADER_CONTEXT='ORDER ENTRY';

 

SELECT *
FROM RA_CUSTOMER_TRX_ALL
WHERE INTERFACE_HEADER_ATTRIBUTE1='602071';

 

SELECT *
FROM AR_CASH_RECEIPTS_ALL
WHERE RECEIPT_NUMBER='1455';

-- CASH_RECEIPT_ID: 271304

SELECT *
FROM GL_JE_HEADERS
WHERE NAME='RAJDEEP_JOURNAL';

--JE_HEADER_ID: 7225894

SELECT * 
FROM GL_JE_HEADERS GJH, GL_JE_LINES GJL
WHERE GJL.JE_HEADER_ID=GJH.JE_HEADER_ID
AND NAME='RAJDEEP_JOURNAL';