-- Q1. Query to list all the responsibilities assigned to the user

SELECT DISTINCT RESPONSIBILITY_NAME
FROM FND_RESPONSIBILITY_TL FRT, FND_USER_RESP_GROUPS_DIRECT FURGD, FND_USER FU 
WHERE FRT.RESPONSIBILITY_ID = FURGD.RESPONSIBILITY_ID 
AND FURGD.USER_ID = FU.USER_ID 
AND FU.USER_NAME = 'XXCTS_RAJDEEP';

--Q2. Query to display the Menu Name assigned to the newly created responsibility

SELECT MENU_NAME
FROM FND_MENUS FM, FND_RESPONSIBILITY FR 
WHERE FM.MENU_ID=FR.MENU_ID 
AND FR.CREATION_DATE=(SELECT MAX(CREATION_DATE)FROM FND_RESPONSIBILITY) 
ORDER BY MENU_NAME;

--TESTING
--SELECT * FROM FND_RESPONSIBILITY WHERE RESPONSIBILITY_ID='68050';

-- Q3. Query to display whether the user is a Person, Employee or Supplier

--SELECT PERSON_PARTY_ID, EMPLOYEE_ID,SUPPLIER_ID FROM FND_USER 
--WHERE USER_NAME='XXCTS_RAJDEEP';

DECLARE
      X_EMPLOYEE FND_USER.EMPLOYEE_ID%TYPE;
      X_CUSTOMER FND_USER.CUSTOMER_ID%TYPE;
      X_SUPPLIER FND_USER.SUPPLIER_ID%TYPE;
      
BEGIN 
      SELECT EMPLOYEE_ID, CUSTOMER_ID, SUPPLIER_ID INTO X_EMPLOYEE, X_CUSTOMER, X_SUPPLIER FROM FND_USER
      WHERE USER_NAME='XXCTS_RAJDEEP';
      
         IF X_EMPLOYEE != NULL THEN
             DBMS_OUTPUT.PUT_LINE('THIS USER IS EMPLOYEE');
         ELSIF X_CUSTOMER != NULL THEN
             DBMS_OUTPUT.PUT_LINE('THIS USER IS CUSTOMER');
         ELSE 
             DBMS_OUTPUT.PUT_LINE('THIS USER IS SUPPLIER');
      END IF;
      
END;

--Q4. List of all Responsibilities

SELECT DISTINCT RESPONSIBILITY_ID, RESPONSIBILITY_NAME FROM FND_RESPONSIBILITY_TL;

--Q5. Query to display the request group name

SELECT DISTINCT REQUEST_GROUP_NAME FROM FND_REQUEST_GROUPS;

--Q6. Query to display the request group name for a specific responsibility.

SELECT REQUEST_GROUP_NAME 
FROM FND_REQUEST_GROUPS FRG, FND_RESPONSIBILITY FR 
WHERE FRG.REQUEST_GROUP_ID=FR.REQUEST_GROUP_ID 
AND FR.RESPONSIBILITY_KEY='XXCTS_RAJDEEP_RESP_MAY22';

--Q7.Query to display the Application name for a Specific Responsibility

SELECT DISTINCT APPLICATION_NAME 
FROM FND_APPLICATION_TL FAT, FND_RESPONSIBILITY FR
WHERE FAT.APPLICATION_ID=FR.APPLICATION_ID 
AND FR.RESPONSIBILITY_KEY='XXCTS_RAJDEEP_RESP_MAY22';

--Q8. Can we join two tables using WHO Columns?



--Q9. Display all the details of a specific USER.

SELECT * FROM FND_USER WHERE USER_NAME='XXCTS_RAJDEEP';

--Q10. Display all the details of a specific Responsibility.

SELECT * FROM FND_RESPONSIBILITY
WHERE RESPONSIBILITY_KEY='XXCTS_RAJDEEP_RESP_MAY22';

