SELECT * FROM FND_USER_RESP_GROUPS_DIRECT; -- USER_ID, RESPONSIBILITY_ID
SELECT * FROM APPLSYS.FND_RESPONSIBILITY; --APPLICATION ID, RESPONSIBILITY_ID
SELECT * FROM APPLSYS.FND_USER; -- USER ID
SELECT * FROM APPLSYS.FND_RESPONSIBILITY_TL; -- RESPONSIBILITY NAME, RESPONSIBILITY ID, APPLICATION ID
SELECT * FROM APPLSYS.FND_APPLICATION_TL; --APPLICATION ID, APPLICATION NAME
SELECT * FROM APPLSYS.FND_APPLICATION; --APPLICATION ID


SELECT DISTINCT
    FRT.RESPONSIBILITY_NAME,
    FU.USER_NAME,
    FURG.START_DATE,
    FURG.END_DATE,
    FR.RESPONSIBILITY_KEY,
    FAT.APPLICATION_NAME
FROM
    FND_USER_RESP_GROUPS_DIRECT FURG,
    APPLSYS.FND_USER FU,
    APPLSYS.FND_RESPONSIBILITY_TL FRT,
    APPLSYS.FND_RESPONSIBILITY FR,
    APPLSYS.FND_APPLICATION_TL FAT,
    APPLSYS.FND_APPLICATION FA
WHERE
        FURG.USER_ID = FU.USER_ID
    AND
        FURG.RESPONSIBILITY_ID = FRT.RESPONSIBILITY_ID
    AND
        FA.APPLICATION_ID = FAT.APPLICATION_ID
    AND
        FRT.APPLICATION_ID = FAT.APPLICATION_ID
    AND
        FU.USER_NAME = 'XXCTS_RAJDEEP'
    AND
        FR.RESPONSIBILITY_KEY = 'XXCTS_RAJDEEP_RESP_MAY22'

ORDER BY FRT.RESPONSIBILITY_NAME;


CREATE OR REPLACE PROCEDURE XXCTS_RAJDEEP_RESP
IS
CURSOR RESP_CUR
IS
SELECT DISTINCT
    FRT.RESPONSIBILITY_NAME,
    FU.USER_NAME,
    FURG.START_DATE,
    FURG.END_DATE,
    FR.RESPONSIBILITY_KEY,
    FAT.APPLICATION_NAME
FROM
    FND_USER_RESP_GROUPS_DIRECT FURG,
    APPLSYS.FND_USER FU,
    APPLSYS.FND_RESPONSIBILITY_TL FRT,
    APPLSYS.FND_RESPONSIBILITY FR,
    APPLSYS.FND_APPLICATION_TL FAT,
    APPLSYS.FND_APPLICATION FA
WHERE
        FURG.USER_ID = FU.USER_ID
    AND
        FURG.RESPONSIBILITY_ID = FRT.RESPONSIBILITY_ID
    AND
        FA.APPLICATION_ID = FAT.APPLICATION_ID
    AND
        FRT.APPLICATION_ID = FAT.APPLICATION_ID
    AND
        FU.USER_NAME = 'XXCTS_RAJDEEP'
    AND
        FR.RESPONSIBILITY_KEY = 'XXCTS_RAJDEEP_RESP_MAY22'

ORDER BY FRT.RESPONSIBILITY_NAME;


RESP_REC RESP_CUR%ROWTYPE;

BEGIN
OPEN RESP_CUR;
DBMS_OUTPUT.PUT_LINE('<?xml version="1.0"?>');
DBMS_OUTPUT.PUT_LINE('<RespRoot>');
LOOP

FETCH RESP_CUR
INTO RESP_REC;

EXIT WHEN RESP_CUR%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('<RESP>');
DBMS_OUTPUT.PUT_LINE('<RESPONSIBILITY_NAME>' || RESP_REC.RESPONSIBILITY_NAME || '</RESPONSIBILITY_NAME>');
DBMS_OUTPUT.PUT_line('<USER_NAME>' || RESP_REC.USER_NAME || '</USER_NAME>');
DBMS_OUTPUT.PUT_LINE('<START_DATE>'|| RESP_REC.START_DATE || '</START_DATE>');
DBMS_OUTPUT.PUT_LINE('<END_DATE>'|| RESP_REC.END_DATE || '</END_DATE>');
DBMS_OUTPUT.PUT_LINE('<RESPONSIBILITY_KEY>'|| RESP_REC.RESPONSIBILITY_KEY || '</RESPONSIBILITY_KEY>');
DBMS_OUTPUT.PUT_LINE('<APPLICATION_NAME>'|| RESP_REC.APPLICATION_NAME || '</APPLICATION_NAME>');
DBMS_OUTPUT.PUT_LINE('</RESP>');
END LOOP;
DBMS_OUTPUT.PUT_LINE('</RespRoot>');
CLOSE RESP_CUR; 
END;



SELECT *
FROM USER_ERRORS
WHERE NAME =upper('XXCTS_RAJDEEP_RESP');
exec XXCTS_RAJDEEP_RESP;


------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE XXCTS_RAJDEEP_RESP(ERRBUF OUT VARCHAR2, RETCODE OUT
VARCHAR2)
IS
CURSOR RESP_CUR
IS
SELECT DISTINCT
    FRT.RESPONSIBILITY_NAME,
    FU.USER_NAME,
    FURG.START_DATE,
    FURG.END_DATE,
    FR.RESPONSIBILITY_KEY,
    FAT.APPLICATION_NAME
FROM
    FND_USER_RESP_GROUPS_DIRECT FURG,
    APPLSYS.FND_USER FU,
    APPLSYS.FND_RESPONSIBILITY_TL FRT,
    APPLSYS.FND_RESPONSIBILITY FR,
    APPLSYS.FND_APPLICATION_TL FAT,
    APPLSYS.FND_APPLICATION FA
WHERE
        FURG.USER_ID = FU.USER_ID
    AND
        FURG.RESPONSIBILITY_ID = FRT.RESPONSIBILITY_ID
    AND
        FA.APPLICATION_ID = FAT.APPLICATION_ID
    AND
        FRT.APPLICATION_ID = FAT.APPLICATION_ID
    AND
        FU.USER_NAME = 'XXCTS_RAJDEEP'
    AND
        FR.RESPONSIBILITY_KEY = 'XXCTS_RAJDEEP_RESP_MAY22'

ORDER BY FRT.RESPONSIBILITY_NAME;

RESP_REC RESP_CUR%ROWTYPE;

V_ERROR_CODE NUMBER;
V_ERR_MESSAGE VARCHAR2(200);

BEGIN
OPEN RESP_CUR;
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<?xml version="1.0"?>');
FND_FILE.PUT_LINE(fnd_file.output,'<RespRoot>');
LOOP

FETCH RESP_CUR
INTO RESP_REC;

EXIT WHEN RESP_CUR%NOTFOUND;
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<RESP>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<RESPONSIBILITY_NAME>' || RESP_REC.RESPONSIBILITY_NAME || '</RESPONSIBILITY_NAME>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<USER_NAME>' || RESP_REC.USER_NAME || '</USER_NAME>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<START_DATE>'|| RESP_REC.START_DATE || '</START_DATE>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<END_DATE>'|| RESP_REC.END_DATE || '</END_DATE>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<RESPONSIBILITY_KEY>'|| RESP_REC.RESPONSIBILITY_KEY || '</RESPONSIBILITY_KEY>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<APPLICATION_NAME>'|| RESP_REC.APPLICATION_NAME || '</APPLICATION_NAME>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'</RESP>');
END LOOP;
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'</RespRoot>');
CLOSE RESP_CUR; 
EXCEPTION

WHEN OTHERS THEN
V_ERROR_CODE := SQLCODE;

V_ERR_MESSAGE := SUBSTR(SQLERRM,1,200);
FND_FILE.PUT_LINE(FND_FILE.LOG, 'Error Code :' || V_ERROR_CODE);
FND_FILE.PUT_LINE(FND_FILE.LOG,'Error Message :' || V_ERR_MESSAGE);
END;

















