SELECT * FROM RA_CUSTOMERS;

SELECT CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_NUMBER, STATUS, CUSTOMER_TYPE, 
NVL(CUSTOMER_CATEGORY_CODE, 'NULL') AS CUSTOMER_CATEGORY_CODE, 
NVL(TAX_CODE, 'NULL') AS TAX_CODE 
FROM RA_CUSTOMERS 
WHERE CUSTOMER_ID BETWEEN 1000 AND 1005; 

SELECT CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_NUMBER, STATUS, CUSTOMER_TYPE, CUSTOMER_CATEGORY_CODE, TAX_CODE 
FROM RA_CUSTOMERS WHERE CUSTOMER_ID BETWEEN 1281 AND 1285; 

-- PL/SQL CODE STARTS HERE:

CREATE OR REPLACE PROCEDURE XXCTS_RAJDEEP_CUSTOMER
IS
CURSOR CUST_CUR
IS
SELECT CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_NUMBER, STATUS, CUSTOMER_TYPE, CUSTOMER_CATEGORY_CODE, TAX_CODE 
FROM RA_CUSTOMERS WHERE CUSTOMER_ID BETWEEN 1281 AND 1285; 

CUST_REC CUST_CUR%ROWTYPE;

BEGIN
OPEN CUST_CUR;
DBMS_OUTPUT.PUT_LINE('<?xml version="1.0"?>');
DBMS_OUTPUT.PUT_LINE('<CustomersRoot>');
LOOP

FETCH CUST_CUR
INTO CUST_REC;

EXIT WHEN CUST_CUR%NOTFOUND;

DBMS_OUTPUT.PUT_LINE('<CUSTOMERS>');
DBMS_OUTPUT.PUT_line('<CUSTOMER_ID>' || CUST_REC.CUSTOMER_ID || '</CUSTOMER_ID>');
DBMS_OUTPUT.PUT_LINE('<CUSTOMER_NAME>' || CUST_REC.CUSTOMER_NAME || '</CUSTOMER_NAME>');
DBMS_OUTPUT.PUT_LINE('<CUSTOMER_NUMBER>'|| CUST_REC.CUSTOMER_NUMBER || '</CUSTOMER_NUMBER>');
DBMS_OUTPUT.PUT_LINE('<STATUS>'|| CUST_REC.STATUS || '</STATUS>');
DBMS_OUTPUT.PUT_LINE('<CUSTOMER_TYPE>'|| CUST_REC.CUSTOMER_TYPE || '</CUSTOMER_TYPE>');
DBMS_OUTPUT.PUT_LINE('<CUSTOMER_CATEGORY_CODE/>');
DBMS_OUTPUT.PUT_LINE('<TAX_CODE/>');
DBMS_OUTPUT.PUT_LINE('</CUSTOMERS>');

END LOOP;
DBMS_OUTPUT.PUT_LINE('</CustomersRoot>');
CLOSE CUST_CUR; 
END;



SELECT *
FROM USER_ERRORS
WHERE NAME =upper('XXCTS_RAJDEEP_CUSTOMER');
exec XXCTS_RAJDEEP_CUSTOMER;

------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE XXCTS_RAJDEEP_CUSTOMER(ERRBUF OUT VARCHAR2, RETCODE OUT
VARCHAR2)

is
cursor CUST_CUR
is
SELECT CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_NUMBER, STATUS, CUSTOMER_TYPE, CUSTOMER_CATEGORY_CODE, TAX_CODE 
FROM RA_CUSTOMERS WHERE CUSTOMER_ID BETWEEN 1281 AND 1285; 

CUST_REC CUST_CUR%ROWTYPE;

V_ERROR_CODE NUMBER;
V_ERR_MESSAGE VARCHAR2(200);
BEGIN
OPEN CUST_CUR;
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<?xml version="1.0"?>');
FND_FILE.PUT_LINE(fnd_file.output,'<CustomersRoot>');
LOOP

FETCH CUST_CUR
INTO CUST_REC;

EXIT WHEN CUST_CUR%NOTFOUND;
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<CUSTOMERS>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<CUSTOMER_ID>' || CUST_REC.CUSTOMER_ID || '</CUSTOMER_ID>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<CUSTOMER_NAME>' || CUST_REC.CUSTOMER_NAME || '</CUSTOMER_NAME>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<CUSTOMER_NUMBER>'|| CUST_REC.CUSTOMER_NUMBER || '</CUSTOMER_NUMBER>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<STATUS>'|| CUST_REC.STATUS || '</STATUS>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<CUSTOMER_TYPE>'|| CUST_REC.CUSTOMER_TYPE || '</CUSTOMER_TYPE>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<CUSTOMER_CATEGORY_CODE>' || CUST_REC.CUSTOMER_CATEGORY_CODE || '</CUSTOMER_CATEGORY_CODE>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<TAX_CODE>' || CUST_REC.TAX_CODE || '</TAX_CODE>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'</CUSTOMERS>');
END LOOP;
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'</CustomersRoot>');
CLOSE CUST_CUR; 
EXCEPTION

WHEN OTHERS THEN
V_ERROR_CODE := SQLCODE;

V_ERR_MESSAGE := SUBSTR(SQLERRM,1,200);
FND_FILE.PUT_LINE(FND_FILE.LOG, 'Error Code :' || V_ERROR_CODE);
FND_FILE.PUT_LINE(FND_FILE.LOG,'Error Message :' || V_ERR_MESSAGE);
end;



