--create table XXCTS_inventory_JUNE
--(NVENTORY_ITEM_ID number, ORGANIZATION_ID number, SEGMENT1 VARCHAR2(20), 
--DESCRIPTION VARCHAR2(20), PURCHASING_ENABLED_FLAG VARCHAR2(1), QUANTITY NUMBER, PRICE NUMBER);
--
--INSERT INTO XXCTS_inventory_JUNE VALUES(934,204,'CM23596','CM23596','Y',200,1000); 
--INSERT INTO XXCTS_inventory_JUNE VALUES(934,916,'CM23596','CM23596','Y',20,3670); 
--INSERT INTO XXCTS_inventory_JUNE VALUES(934,917,'CM23596','CM23596','Y',500,10000); 
--INSERT INTO XXCTS_inventory_JUNE VALUES(934,208,'CM23596','CM23596','Y',20,150000);

select * from xxcts_inventory_JUNE ;

SELECT INVENTORY_ITEM_ID, ORGANIZATION_ID, SEGMENT1, DESCRIPTION, PURCHASING_ENABLED_FLAG, QUANTITY, PRICE FROM XXCTS_INVENTORY_JUNE; 



CREATE OR REPLACE PROCEDURE XXCTS_RAJDEEP_INVENTORY_JUNE
IS
CURSOR INV_CUR
IS
SELECT INVENTORY_ITEM_ID, ORGANIZATION_ID, SEGMENT1, DESCRIPTION, 
PURCHASING_ENABLED_FLAG, QUANTITY, PRICE 
FROM XXCTS_INVENTORY_JUNE; 

INV_REC INV_CUR%ROWTYPE;

BEGIN
OPEN INV_CUR;
DBMS_OUTPUT.PUT_LINE('<?xml version="1.0"?>');
DBMS_OUTPUT.PUT_LINE('<ITEMROOT>');
LOOP

FETCH INV_CUR
INTO INV_REC;

EXIT WHEN INV_CUR%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('<ITEM>');
DBMS_OUTPUT.PUT_line('<INVENTORY_ITEM_ID>' || INV_REC.INVENTORY_ITEM_ID || '</INVENTORY_ITEM_ID>');
DBMS_OUTPUT.PUT_LINE('<ORGANIZATION_ID>' || INV_REC.ORGANIZATION_ID || '</ORGANIZATION_ID>');
DBMS_OUTPUT.PUT_LINE('<SEGMENT1>'|| INV_REC.SEGMENT1 || '</SEGMENT1>');
DBMS_OUTPUT.PUT_LINE('<DESCRIPTION>'|| INV_REC.DESCRIPTION || '</DESCRIPTION>');
DBMS_OUTPUT.PUT_LINE('<PURCHASING_ENABLED_FLAG>'|| INV_REC.PURCHASING_ENABLED_FLAG || '</PURCHASING_ENABLED_FLAG>');
DBMS_OUTPUT.PUT_LINE('<QUANTITY>'|| INV_REC.QUANTITY || '</QUANTITY>');
DBMS_OUTPUT.PUT_LINE('<PRICE>'|| INV_REC.PRICE || '</PRICE>');
DBMS_OUTPUT.PUT_LINE('</ITEM>');
END LOOP;
DBMS_OUTPUT.PUT_LINE('</ITEMROOT>');
CLOSE INV_CUR; 
END;



SELECT *
FROM USER_ERRORS
WHERE NAME =upper('XXCTS_RAJDEEP_INVENTORY_JUNE');
exec XXCTS_RAJDEEP_INVENTORY_JUNE;

-------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE XXCTS_RAJDEEP_INVENTORY_JUNE(ERRBUF OUT VARCHAR2, RETCODE OUT
VARCHAR2)
IS
CURSOR INV_CUR
IS
SELECT INVENTORY_ITEM_ID, ORGANIZATION_ID, SEGMENT1, DESCRIPTION, 
PURCHASING_ENABLED_FLAG, QUANTITY, PRICE 
FROM XXCTS_INVENTORY_JUNE; 

INV_REC INV_CUR%ROWTYPE;

V_ERROR_CODE NUMBER;
V_ERR_MESSAGE VARCHAR2(200);

BEGIN
OPEN INV_CUR;
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<?xml version="1.0"?>');
FND_FILE.PUT_LINE(fnd_file.output,'<ITEMROOT>');
LOOP

FETCH INV_CUR
INTO INV_REC;

EXIT WHEN INV_CUR%NOTFOUND;
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<ITEM>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<INVENTORY_ITEM_ID>' || INV_REC.INVENTORY_ITEM_ID || '</INVENTORY_ITEM_ID>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<ORGANIZATION_ID>' || INV_REC.ORGANIZATION_ID || '</ORGANIZATION_ID>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<SEGMENT1>'|| INV_REC.SEGMENT1 || '</SEGMENT1>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<DESCRIPTION>'|| INV_REC.DESCRIPTION || '</DESCRIPTION>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<PURCHASING_ENABLED_FLAG>'|| INV_REC.PURCHASING_ENABLED_FLAG || '</PURCHASING_ENABLED_FLAG>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<QUANTITY>'|| INV_REC.QUANTITY || '</QUANTITY>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'<PRICE>'|| INV_REC.PRICE || '</PRICE>');
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'</ITEM>');
END LOOP;
FND_FILE.PUT_LINE(FND_FILE.OUTPUT,'</ITEMROOT>');
CLOSE INV_CUR; 
EXCEPTION

WHEN OTHERS THEN
V_ERROR_CODE := SQLCODE;

V_ERR_MESSAGE := SUBSTR(SQLERRM,1,200);
FND_FILE.PUT_LINE(FND_FILE.LOG, 'Error Code :' || V_ERROR_CODE);
FND_FILE.PUT_LINE(FND_FILE.LOG,'Error Message :' || V_ERR_MESSAGE);
end;

